services:
  - name: selenium-app
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PORT
        value: 10000
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
    autoDeploy: true
    region: oregon  # Pode mudar para frankfurt se precisar
    plan: free
